# Explicit allowlists of upstream Xournal++ sources compiled into the Qt build (no globbing, so an
# upstream merge never silently pulls GTK code into the Qt build). See qt/docs/adr/0002-upstream-seams.md.
set(XOJ_SRC "${XOJ_UPSTREAM_DIR}/src")

# util: everything except GTK widgets/dialog helpers (replaced by qt/compat).
set(XOJ_UTIL_SOURCES
    ${XOJ_SRC}/util/Assert.cpp
    ${XOJ_SRC}/util/Color.cpp
    ${XOJ_SRC}/util/ElementRange.cpp
    ${XOJ_SRC}/util/GzInputStream.cpp
    ${XOJ_SRC}/util/GzUtil.cpp
    ${XOJ_SRC}/util/logger/Logger.cpp
    ${XOJ_SRC}/util/Matrix.cpp
    ${XOJ_SRC}/util/NamedColor.cpp
    ${XOJ_SRC}/util/OutputStream.cpp
    ${XOJ_SRC}/util/PathUtil.cpp
    ${XOJ_SRC}/util/PlaceholderString.cpp
    ${XOJ_SRC}/util/raii/CStringWrapper.cpp
    ${XOJ_SRC}/util/Range.cpp
    ${XOJ_SRC}/util/Recolor.cpp
    ${XOJ_SRC}/util/Rectangle.cpp
    ${XOJ_SRC}/util/SaveNameUtils.cpp
    ${XOJ_SRC}/util/serializing/BinObjectEncoding.cpp
    ${XOJ_SRC}/util/serializing/HexObjectEncoding.cpp
    ${XOJ_SRC}/util/serializing/InputStreamException.cpp
    ${XOJ_SRC}/util/serializing/ObjectEncoding.cpp
    ${XOJ_SRC}/util/serializing/ObjectInputStream.cpp
    ${XOJ_SRC}/util/serializing/ObjectOutputStream.cpp
    ${XOJ_SRC}/util/Stacktrace.cpp
    ${XOJ_SRC}/util/StringUtils.cpp
    ${XOJ_SRC}/util/Util.cpp
    ${XOJ_SRC}/util/XojPreviewExtractor.cpp
    ${XOJ_SRC}/util/ZipInputStream.cpp
)

# core: document model, file I/O, rendering views, PDF backend + export, settings, shape recognizer.
set(XOJ_CORE_SOURCES
    ${XOJ_SRC}/core/control/DeviceListHelper.cpp
    ${XOJ_SRC}/core/control/ExportHelper.cpp
    ${XOJ_SRC}/core/control/jobs/ImageExport.cpp
    ${XOJ_SRC}/core/control/pagetype/PageTypeHandler.cpp
    ${XOJ_SRC}/core/control/PdfCache.cpp
    ${XOJ_SRC}/core/control/settings/ButtonConfig.cpp
    ${XOJ_SRC}/core/control/settings/LatexSettings.cpp
    ${XOJ_SRC}/core/control/settings/MetadataManager.cpp
    ${XOJ_SRC}/core/control/settings/PageTemplateSettings.cpp
    ${XOJ_SRC}/core/control/settings/Settings.cpp
    ${XOJ_SRC}/core/control/settings/SettingsEnums.cpp
    ${XOJ_SRC}/core/control/settings/ViewModes.cpp
    ${XOJ_SRC}/core/control/shaperecognizer/CircleRecognizer.cpp
    ${XOJ_SRC}/core/control/shaperecognizer/Inertia.cpp
    ${XOJ_SRC}/core/control/shaperecognizer/RecoSegment.cpp
    ${XOJ_SRC}/core/control/shaperecognizer/ShapeRecognizer.cpp
    ${XOJ_SRC}/core/control/ToolBase.cpp
    ${XOJ_SRC}/core/control/Tool.cpp
    ${XOJ_SRC}/core/control/ToolEnums.cpp
    ${XOJ_SRC}/core/control/ToolHandler.cpp
    ${XOJ_SRC}/core/control/xml/Attribute.cpp
    ${XOJ_SRC}/core/control/xml/DoubleArrayAttribute.cpp
    ${XOJ_SRC}/core/control/xml/DoubleAttribute.cpp
    ${XOJ_SRC}/core/control/xml/IntAttribute.cpp
    ${XOJ_SRC}/core/control/xml/SizeTAttribute.cpp
    ${XOJ_SRC}/core/control/xml/TextAttribute.cpp
    ${XOJ_SRC}/core/control/xml/XmlImageNode.cpp
    ${XOJ_SRC}/core/control/xml/XmlNode.cpp
    ${XOJ_SRC}/core/control/xml/XmlPointNode.cpp
    ${XOJ_SRC}/core/control/xml/XmlTexNode.cpp
    ${XOJ_SRC}/core/control/xml/XmlTextNode.cpp
    ${XOJ_SRC}/core/control/xojfile/LoadHandler.cpp
    ${XOJ_SRC}/core/control/xojfile/SaveHandler.cpp
    ${XOJ_SRC}/core/control/xojfile/XmlParser.cpp
    ${XOJ_SRC}/core/control/xojfile/XmlParserHelper.cpp
    ${XOJ_SRC}/core/control/xojfile/XojExportHandler.cpp
    ${XOJ_SRC}/core/gui/GladeSearchpath.cpp
    ${XOJ_SRC}/core/gui/LayoutMapper.cpp
    ${XOJ_SRC}/core/gui/toolbarMenubar/model/ColorPalette.cpp
    ${XOJ_SRC}/core/model/AudioContent.cpp
    ${XOJ_SRC}/core/model/BackgroundConfig.cpp
    ${XOJ_SRC}/core/model/BackgroundImage.cpp
    ${XOJ_SRC}/core/model/Document.cpp
    ${XOJ_SRC}/core/model/DocumentHandler.cpp
    ${XOJ_SRC}/core/model/DocumentListener.cpp
    ${XOJ_SRC}/core/model/Element.cpp
    ${XOJ_SRC}/core/model/eraser/ErasableStroke.cpp
    ${XOJ_SRC}/core/model/eraser/ErasableStrokeOverlapTree.cpp
    ${XOJ_SRC}/core/model/Font.cpp
    ${XOJ_SRC}/core/model/FormatDefinitions.cpp
    ${XOJ_SRC}/core/model/Image.cpp
    ${XOJ_SRC}/core/model/Layer.cpp
    ${XOJ_SRC}/core/model/LineStyle.cpp
    ${XOJ_SRC}/core/model/Link.cpp
    ${XOJ_SRC}/core/model/LinkDestination.cpp
    ${XOJ_SRC}/core/model/MathVect.cpp
    ${XOJ_SRC}/core/model/PageHandler.cpp
    ${XOJ_SRC}/core/model/PageListener.cpp
    ${XOJ_SRC}/core/model/PageType.cpp
    ${XOJ_SRC}/core/model/PaperSize.cpp
    ${XOJ_SRC}/core/model/Point.cpp
    ${XOJ_SRC}/core/model/RectangularElement.cpp
    ${XOJ_SRC}/core/model/Snapping.cpp
    ${XOJ_SRC}/core/model/SplineSegment.cpp
    ${XOJ_SRC}/core/model/StrokeContour.cpp
    ${XOJ_SRC}/core/model/Stroke.cpp
    ${XOJ_SRC}/core/model/StrokeStyle.cpp
    ${XOJ_SRC}/core/model/TexImage.cpp
    ${XOJ_SRC}/core/model/Text.cpp
    ${XOJ_SRC}/core/model/XojPage.cpp
    ${XOJ_SRC}/core/pdf/base/HybridPdfExport.cpp
    ${XOJ_SRC}/core/pdf/base/PdfExportBackend.cpp
    ${XOJ_SRC}/core/pdf/base/QPdfExport.cpp
    ${XOJ_SRC}/core/pdf/base/XojCairoPdfExport.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfAction.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfBookmarkIterator.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfDocument.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfDocumentInterface.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfExport.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfExportFactory.cpp
    ${XOJ_SRC}/core/pdf/base/XojPdfPage.cpp
    ${XOJ_SRC}/core/pdf/popplerapi/PopplerGlibAction.cpp
    ${XOJ_SRC}/core/pdf/popplerapi/PopplerGlibDocument.cpp
    ${XOJ_SRC}/core/pdf/popplerapi/PopplerGlibPageBookmarkIterator.cpp
    ${XOJ_SRC}/core/pdf/popplerapi/PopplerGlibPage.cpp
    ${XOJ_SRC}/core/view/background/BackgroundView.cpp
    ${XOJ_SRC}/core/view/background/BaseIsometricBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/DottedBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/GraphBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/ImageBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/IsoDottedBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/IsoGraphBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/LinedBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/OneColorBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/PdfBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/PlainBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/RuledBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/StavesBackgroundView.cpp
    ${XOJ_SRC}/core/view/background/TransparentCheckerboardBackgroundView.cpp
    ${XOJ_SRC}/core/view/DocumentView.cpp
    ${XOJ_SRC}/core/view/ElementContainerView.cpp
    ${XOJ_SRC}/core/view/ElementView.cpp
    ${XOJ_SRC}/core/view/ErasableStrokeView.cpp
    ${XOJ_SRC}/core/view/ImageView.cpp
    ${XOJ_SRC}/core/view/LayerView.cpp
    ${XOJ_SRC}/core/view/LinkView.cpp
    ${XOJ_SRC}/core/view/Mask.cpp
    ${XOJ_SRC}/core/view/StrokeView.cpp
    ${XOJ_SRC}/core/view/StrokeViewHelper.cpp
    ${XOJ_SRC}/core/view/TexImageView.cpp
    ${XOJ_SRC}/core/view/TextView.cpp
    # undo + layer logic: compiled against the shadow Control/XournalView/... interfaces (qt/compat/include)
    ${XOJ_SRC}/core/control/layer/LayerController.cpp
    ${XOJ_SRC}/core/control/layer/LayerCtrlListener.cpp
    ${XOJ_SRC}/core/undo/AddUndoAction.cpp
    ${XOJ_SRC}/core/undo/ArrangeUndoAction.cpp
    ${XOJ_SRC}/core/undo/ColorUndoAction.cpp
    ${XOJ_SRC}/core/undo/DeleteUndoAction.cpp
    ${XOJ_SRC}/core/undo/EmergencySaveRestore.cpp
    ${XOJ_SRC}/core/undo/EraseUndoAction.cpp
    ${XOJ_SRC}/core/undo/FillUndoAction.cpp
    ${XOJ_SRC}/core/undo/FontUndoAction.cpp
    ${XOJ_SRC}/core/undo/GroupUndoAction.cpp
    ${XOJ_SRC}/core/undo/InsertDeletePageUndoAction.cpp
    ${XOJ_SRC}/core/undo/InsertLayerUndoAction.cpp
    ${XOJ_SRC}/core/undo/InsertUndoAction.cpp
    ${XOJ_SRC}/core/undo/LayerRenameUndoAction.cpp
    ${XOJ_SRC}/core/undo/LineStyleUndoAction.cpp
    ${XOJ_SRC}/core/undo/MergeLayerDownUndoAction.cpp
    ${XOJ_SRC}/core/undo/MissingPdfUndoAction.cpp
    ${XOJ_SRC}/core/undo/MoveLayerUndoAction.cpp
    ${XOJ_SRC}/core/undo/MoveSelectionToLayerUndoAction.cpp
    ${XOJ_SRC}/core/undo/MoveUndoAction.cpp
    ${XOJ_SRC}/core/undo/PageBackgroundChangedUndoAction.cpp
    ${XOJ_SRC}/core/undo/PageSizeChangeUndoAction.cpp
    ${XOJ_SRC}/core/undo/RecognizerUndoAction.cpp
    ${XOJ_SRC}/core/undo/RemoveLayerUndoAction.cpp
    ${XOJ_SRC}/core/undo/RotateUndoAction.cpp
    ${XOJ_SRC}/core/undo/ScaleUndoAction.cpp
    ${XOJ_SRC}/core/undo/SizeUndoAction.cpp
    ${XOJ_SRC}/core/undo/SwapUndoAction.cpp
    ${XOJ_SRC}/core/undo/TextBoxUndoAction.cpp
    ${XOJ_SRC}/core/undo/UndoAction.cpp
    ${XOJ_SRC}/core/undo/UndoRedoHandler.cpp
)

# tools: upstream input handlers and their overlay views, compiled unmodified against the shadow interfaces
set(XOJ_TOOLS_SOURCES
    ${XOJ_SRC}/core/control/tools/InputHandler.cpp
    ${XOJ_SRC}/core/control/tools/StrokeHandler.cpp
    ${XOJ_SRC}/core/control/tools/StrokeStabilizer.cpp
    ${XOJ_SRC}/core/control/tools/SnapToGridInputHandler.cpp
    ${XOJ_SRC}/core/control/tools/EraseHandler.cpp
    ${XOJ_SRC}/core/control/zoom/ZoomListener.cpp
    ${XOJ_SRC}/core/control/tools/BaseShapeHandler.cpp
    ${XOJ_SRC}/core/control/tools/RulerHandler.cpp
    ${XOJ_SRC}/core/control/tools/RectangleHandler.cpp
    ${XOJ_SRC}/core/control/tools/EllipseHandler.cpp
    ${XOJ_SRC}/core/control/tools/ArrowHandler.cpp
    ${XOJ_SRC}/core/control/tools/CoordinateSystemHandler.cpp
    ${XOJ_SRC}/core/control/tools/SplineHandler.cpp
    ${XOJ_SRC}/core/view/overlays/BaseShapeOrSplineToolView.cpp
    ${XOJ_SRC}/core/view/overlays/ShapeToolView.cpp
    ${XOJ_SRC}/core/view/overlays/SplineToolView.cpp
    ${XOJ_SRC}/core/control/tools/Selector.cpp
    ${XOJ_SRC}/core/control/tools/EditSelection.cpp
    ${XOJ_SRC}/core/control/tools/EditSelectionContents.cpp
    ${XOJ_SRC}/core/view/overlays/SelectorView.cpp
    ${XOJ_SRC}/core/control/tools/PdfElemSelection.cpp
    ${XOJ_SRC}/core/view/overlays/PdfElementSelectionView.cpp
    ${XOJ_SRC}/core/view/overlays/BaseStrokeToolView.cpp
    ${XOJ_SRC}/core/view/overlays/StrokeToolView.cpp
    ${XOJ_SRC}/core/view/overlays/StrokeToolFilledView.cpp
    ${XOJ_SRC}/core/view/overlays/StrokeToolFilledHighlighterView.cpp
    ${XOJ_SRC}/core/gui/inputdevices/InputUtils.cpp
    ${XOJ_SRC}/core/gui/inputdevices/PositionInputData.cpp
    ${XOJ_SRC}/core/gui/LegacyRedrawable.cpp
)
