#!/usr/bin/env bash
# xournal-qt: build environment for a Claude Code cloud container (Ubuntu 24.04, Qt 6.4 in apt = too old).
#
# Creates a self-contained conda-forge environment under /opt/xqt-env (outside the repo) with Qt 6 (>= 6.5), the C
# libraries of the core, qpdf 12 (used with -DXQT_SYSTEM_QPDF=ON, so nothing is downloaded from GitHub at configure),
# ccache >= 4.7, cmake, ninja and conda-forge's GCC, all ABI-consistent; GoogleTest is built from Ubuntu's
# `googletest` source package (FetchContent's GitHub download is blocked). Idempotent: re-running it only fills in
# what is missing. Needs no change to the repository.
#
#   bash cloud-env.sh                 # set up (or check) the environment, write cloud-env.env next to this script
#   bash cloud-env.sh --configure     # ... and also configure build-qt in the repo
#   source /opt/xqt-env/cloud-env.env # in any later shell: PATH, CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, XQT_CMAKE_ARGS
#
# Only conda.anaconda.org is needed (outbound via the session's HTTPS proxy; the CA bundle comes from SSL_CERT_FILE).
set -euo pipefail

XQT_ENV_ROOT="${XQT_ENV_ROOT:-/opt/xqt-env}"
MAMBA_ROOT_PREFIX="${XQT_ENV_ROOT}/mamba"
ENV_PREFIX="${XQT_ENV_ROOT}/env"
MM="${XQT_ENV_ROOT}/bootstrap/bin/micromamba"
MM_VERSION="${XQT_MM_VERSION:-2.9.0-0}"
REPO="${XQT_REPO:-/home/user/xournal-qt}"
QT_SPEC="${XQT_QT_SPEC:-qt6-main=6.9}"
export MAMBA_ROOT_PREFIX

ca="${SSL_CERT_FILE:-/root/.ccr/ca-bundle.crt}"

# 1. micromamba, from the conda-forge package itself (micro.mamba.pm / GitHub are blocked here)
if [ ! -x "$MM" ]; then
    mkdir -p "${XQT_ENV_ROOT}/bootstrap"
    curl -fsSL --retry 3 -o "${XQT_ENV_ROOT}/bootstrap/mm.tar.bz2" \
        "https://conda.anaconda.org/conda-forge/linux-64/micromamba-${MM_VERSION}.tar.bz2"
    tar -xjf "${XQT_ENV_ROOT}/bootstrap/mm.tar.bz2" -C "${XQT_ENV_ROOT}/bootstrap" bin/micromamba
    rm -f "${XQT_ENV_ROOT}/bootstrap/mm.tar.bz2"
fi

packages=(
    "$QT_SPEC"
    # recording and playing audio (qt/audio, optional: without it the app offers no recording)
    "qt6-multimedia=${QT_SPEC#qt6-main=}"
    # the C libraries of the core (qt/cmake/XojDeps.cmake), qpdf 12 (XqtQpdf.cmake), GoogleTest: see below
    poppler cairo pango glib gdk-pixbuf fontconfig expat libxml2 libxml2-devel libzip zlib libjpeg-turbo "qpdf>=12"
    # OpenGL/EGL headers and X/xkb libraries that Qt6Gui's CMake package looks for
    libgl-devel libegl-devel libxkbcommon xorg-libx11
    # fonts for the off-screen tests (QML text, Pango)
    fonts-conda-ecosystem font-ttf-dejavu-sans-mono
    # tools
    "c-compiler" "cxx-compiler" "cmake>=3.28" ninja pkg-config "ccache>=4.7" make
)

if [ ! -x "${ENV_PREFIX}/bin/qmake6" ] && [ ! -x "${ENV_PREFIX}/bin/qmake" ]; then
    "$MM" create -y -p "$ENV_PREFIX" -c conda-forge --override-channels --ssl-verify "$ca" "${packages[@]}"
else
    # already there: install whatever is missing (no-op when complete)
    "$MM" install -y -p "$ENV_PREFIX" -c conda-forge --override-channels --ssl-verify "$ca" "${packages[@]}" \
        | tail -3
fi

# conda-forge's gtest is compiled as C++17 and lacks the char8_t printers this C++20 project links against, and
# FetchContent's GitHub download is blocked: build GoogleTest from Ubuntu's source package instead (FetchContent with
# FETCHCONTENT_SOURCE_DIR_GOOGLETEST, find_package(GTest) disabled). Make sure no conda gtest shadows its headers.
"$MM" remove -y -p "$ENV_PREFIX" gtest >/dev/null 2>&1 || true
if [ ! -f /usr/src/googletest/CMakeLists.txt ]; then
    SUDO=""; [ "$(id -u)" = 0 ] || SUDO=sudo
    $SUDO apt-get install -y --no-install-recommends googletest \
        || { $SUDO apt-get update && $SUDO apt-get install -y --no-install-recommends googletest; }
fi

# 2. the env file other sessions source
envfile="${XQT_ENV_ROOT}/cloud-env.env"
cat > "$envfile" <<EOF
# xournal-qt cloud build environment (generated by cloud-env.sh). Usage: source ${envfile}
export XQT_ENV_PREFIX="${ENV_PREFIX}"
export CONDA_PREFIX="${ENV_PREFIX}"
export PATH="${ENV_PREFIX}/bin:\${PATH#${ENV_PREFIX}/bin:}"
export CMAKE_PREFIX_PATH="${ENV_PREFIX}"
export PKG_CONFIG_PATH="${ENV_PREFIX}/lib/pkgconfig:${ENV_PREFIX}/share/pkgconfig"
export PKG_CONFIG_LIBDIR="${ENV_PREFIX}/lib/pkgconfig:${ENV_PREFIX}/share/pkgconfig"
export CC="${ENV_PREFIX}/bin/x86_64-conda-linux-gnu-cc"
export CXX="${ENV_PREFIX}/bin/x86_64-conda-linux-gnu-c++"
# conda-forge's fontconfig: use the env's fonts.conf (Pango, Qt)
export FONTCONFIG_FILE="${ENV_PREFIX}/etc/fonts/fonts.conf"
export FONTCONFIG_PATH="${ENV_PREFIX}/etc/fonts"
# Qt wants a UTF-8 locale (the container has LANG unset / C)
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
# tests run off-screen
export QT_QPA_PLATFORM=offscreen
export CCACHE_DIR="\${CCACHE_DIR:-\$HOME/.cache/ccache}"
export CCACHE_MAXSIZE="\${CCACHE_MAXSIZE:-10G}"
# configure flags: qpdf from the env (no GitHub download), libs from the env; RPATH to the env's lib
export XQT_CMAKE_ARGS="-G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DXQT_SYSTEM_QPDF=ON -DCMAKE_PREFIX_PATH=${ENV_PREFIX} -DCMAKE_INSTALL_RPATH=${ENV_PREFIX}/lib -DCMAKE_BUILD_RPATH=${ENV_PREFIX}/lib -DCMAKE_DISABLE_FIND_PACKAGE_GTest=ON -DFETCHCONTENT_SOURCE_DIR_GOOGLETEST=/usr/src/googletest"
EOF
here="$(dirname "$(readlink -f "$0")")"
cp -f "$envfile" "$here/cloud-env.env" 2>/dev/null || true
[ "$(readlink -f "$0")" = "${XQT_ENV_ROOT}/cloud-env.sh" ] || cp -f "$0" "${XQT_ENV_ROOT}/cloud-env.sh"

# shellcheck disable=SC1090
source "$envfile"
echo "xqt-env: Qt $(qmake6 -query QT_VERSION 2>/dev/null || qmake -query QT_VERSION), $(cmake --version | head -1)," \
     "ccache $(ccache --version | head -1 | awk '{print $3}'), qpdf $(pkg-config --modversion libqpdf)," \
     "$($CXX --version | head -1)"

if [ "${1:-}" = --configure ]; then
    # shellcheck disable=SC2086
    cmake -S "$REPO/qt" -B "$REPO/build-qt" $XQT_CMAKE_ARGS
fi
