#include "ArchivePdf.h"

#include <algorithm>
#include <ctime>
#include <map>
#include <regex>
#include <set>
#include <sstream>

#include <qpdf/QPDFEFStreamObjectHelper.hh>
#include <qpdf/QPDFEmbeddedFileDocumentHelper.hh>
#include <qpdf/QPDFFileSpecObjectHelper.hh>
#include <qpdf/QPDFObjectHandle.hh>
#include <qpdf/QPDFPageDocumentHelper.hh>
#include <qpdf/QPDFPageObjectHelper.hh>

#include "util/PlaceholderString.h"
#include "util/i18n.h"

#include "config.h"

namespace xqt::ArchivePdf {

// The bytes of qt/resources/icc/sRGB.icc (generated by CMake: XqtSession.cmake)
extern const unsigned char SRGB_ICC[];
extern const unsigned long SRGB_ICC_SIZE;

namespace {

using OH = QPDFObjectHandle;

std::string lower(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    return s;
}

bool isName(OH o, const char* name) { return o.isName() && o.getName() == name; }

/// A name, or an array holding it (filters).
bool hasName(OH o, std::initializer_list<const char*> names) {
    if (o.isName()) {
        return std::any_of(names.begin(), names.end(), [&](const char* n) { return o.getName() == n; });
    }
    if (o.isArray()) {
        for (int i = 0; i < o.getArrayNItems(); ++i) {
            if (hasName(o.getArrayItem(i), names)) {
                return true;
            }
        }
    }
    return false;
}

void removeKeys(OH dict, std::initializer_list<const char*> keys) {
    for (const char* k: keys) {
        if (dict.hasKey(k)) {
            dict.removeKey(k);
        }
    }
}

/// A colour space that is (or falls back on) DeviceCMYK: not allowed with an RGB output intent.
bool cmykSpace(OH cs, int depth = 0) {
    if (depth > 8) {
        return false;
    }
    if (cs.isName()) {
        return cs.getName() == "/DeviceCMYK" || cs.getName() == "/CMYK";
    }
    if (!cs.isArray() || cs.getArrayNItems() == 0 || !cs.getArrayItem(0).isName()) {
        return false;
    }
    const std::string family = cs.getArrayItem(0).getName();
    if (family == "/Indexed" || family == "/I" || family == "/Pattern") {
        return cs.getArrayNItems() > 1 && cmykSpace(cs.getArrayItem(1), depth + 1);
    }
    if (family == "/Separation" || family == "/DeviceN") {
        return cs.getArrayNItems() > 2 && cmykSpace(cs.getArrayItem(2), depth + 1);
    }
    return false;
}

/// Actions PDF/A-2 and -3 forbid (ISO 19005-2, 6.6.1), and named actions other than the four page ones.
bool forbiddenAction(OH action, int depth = 0) {
    if (depth > 16 || !action.isDictionary()) {
        return false;
    }
    OH s = action.getKey("/S");
    if (s.isName()) {
        static const std::set<std::string> bad = {"/Launch", "/Sound", "/Movie", "/ResetForm", "/ImportData",
                                                  "/Hide", "/SetOCGState", "/Rendition", "/Trans", "/GoTo3DView",
                                                  "/JavaScript", "/RichMediaExecute"};
        if (bad.count(s.getName())) {
            return true;
        }
        if (s.getName() == "/Named") {
            OH n = action.getKey("/N");
            static const std::set<std::string> ok = {"/NextPage", "/PrevPage", "/FirstPage", "/LastPage"};
            if (!n.isName() || !ok.count(n.getName())) {
                return true;
            }
        }
    }
    OH next = action.getKey("/Next");
    if (next.isDictionary()) {
        return forbiddenAction(next, depth + 1);
    }
    if (next.isArray()) {
        for (int i = 0; i < next.getArrayNItems(); ++i) {
            if (forbiddenAction(next.getArrayItem(i), depth + 1)) {
                return true;
            }
        }
    }
    return false;
}

/// Operators of a content stream: CMYK colours, inline images PDF/A does not allow.
struct ContentScan: OH::ParserCallbacks {
    std::vector<OH> args;
    bool cmyk = false, badInline = false;
    void handleObject(OH o) override {
        if (o.isOperator()) {
            const std::string op = o.getOperatorValue();
            if (op == "k" || op == "K") {
                cmyk = true;
            } else if ((op == "cs" || op == "CS") && !args.empty() && cmykSpace(args.back())) {
                cmyk = true;
            } else if (op == "ID") {  // an inline image: its dictionary is the operands
                for (size_t i = 0; i + 1 < args.size(); i += 2) {
                    if (!args[i].isName()) {
                        continue;
                    }
                    const std::string k = args[i].getName();
                    OH v = args[i + 1];
                    if ((k == "/CS" || k == "/ColorSpace") && cmykSpace(v)) {
                        cmyk = true;
                    } else if ((k == "/I" || k == "/Interpolate") && v.isBool() && v.getBoolValue()) {
                        badInline = true;
                    } else if ((k == "/F" || k == "/Filter") && hasName(v, {"/LZW", "/LZWDecode"})) {
                        badInline = true;
                    }
                }
            }
            args.clear();
        } else if (!o.isInlineImage()) {
            args.push_back(o);
        }
    }
    void handleEOF() override {}
};

enum class Problem { Cmyk, NoAppearance, AnnotKind, PostScript, Reference, External, Inline };

/// A form field's type (/FT, inherited from its parents).
std::string fieldType(OH field) {
    for (int depth = 0; field.isDictionary() && depth < 32; ++depth) {
        if (OH ft = field.getKey("/FT"); ft.isName()) {
            return ft.getName();
        }
        field = field.getKey("/Parent");
    }
    return {};
}

/// Walks everything a page shows: checks it, and repairs what can be repaired.
struct Walker {
    std::set<QPDFObjGen> seen;
    std::set<std::string> fontsMissing;
    std::map<Problem, std::set<int>> problems;  ///< the pages (1-based) each was found on
    bool removedActions = false, removedHidden = false;
    int page = 0;

    bool once(OH o) { return !o.isIndirect() || seen.insert(o.getObjGen()).second; }
    void problem(Problem p) { problems[p].insert(page); }

    void content(OH streamOrArray, bool defaultCmyk) {
        ContentScan scan;
        try {
            OH::parseContentStream(streamOrArray, &scan);
        } catch (const std::exception&) {
            return;  // (a broken stream: shown as far as it goes, as by any viewer)
        }
        if (scan.cmyk && !defaultCmyk) {
            problem(Problem::Cmyk);
        }
        if (scan.badInline) {
            problem(Problem::Inline);
        }
    }

    /// Whether a resource dictionary makes DeviceCMYK device independent (/DefaultCMYK).
    static bool hasDefaultCmyk(OH res) {
        return res.isDictionary() && res.getKey("/ColorSpace").isDictionary() &&
               res.getKey("/ColorSpace").hasKey("/DefaultCMYK");
    }

    void resources(OH res) {
        if (!res.isDictionary() || !once(res)) {
            return;
        }
        const bool defaultCmyk = hasDefaultCmyk(res);
        if (OH cs = res.getKey("/ColorSpace"); cs.isDictionary()) {
            for (const auto& k: cs.getKeys()) {
                if (k != "/DefaultCMYK" && cmykSpace(cs.getKey(k)) && !defaultCmyk) {
                    problem(Problem::Cmyk);
                }
            }
        }
        if (OH fonts = res.getKey("/Font"); fonts.isDictionary()) {
            for (const auto& k: fonts.getKeys()) {
                font(fonts.getKey(k));
            }
        }
        if (OH xobjects = res.getKey("/XObject"); xobjects.isDictionary()) {
            for (const auto& k: xobjects.getKeys()) {
                xobject(xobjects.getKey(k), defaultCmyk);
            }
        }
        if (OH states = res.getKey("/ExtGState"); states.isDictionary()) {
            for (const auto& k: states.getKeys()) {
                graphicsState(states.getKey(k));
            }
        }
        if (OH patterns = res.getKey("/Pattern"); patterns.isDictionary()) {
            for (const auto& k: patterns.getKeys()) {
                pattern(patterns.getKey(k), defaultCmyk);
            }
        }
        if (OH shadings = res.getKey("/Shading"); shadings.isDictionary()) {
            for (const auto& k: shadings.getKeys()) {
                shading(shadings.getKey(k), defaultCmyk);
            }
        }
    }

    void font(OH f) {
        if (!f.isDictionary() || !once(f)) {
            return;
        }
        OH subtype = f.getKey("/Subtype");
        if (isName(subtype, "/Type3")) {
            resources(f.getKey("/Resources"));  // (its glyphs are content)
            return;
        }
        OH descriptor = f.getKey("/FontDescriptor");
        if (isName(subtype, "/Type0")) {
            OH descendants = f.getKey("/DescendantFonts");
            descriptor = descendants.isArray() && descendants.getArrayNItems() > 0
                                 ? descendants.getArrayItem(0).getKey("/FontDescriptor")
                                 : OH::newNull();
        }
        if (descriptor.isDictionary()) {
            // (optional in PDF/A-2 and -3, and wrong when a subset lists glyphs it lost or kept)
            removeKeys(descriptor, {"/CharSet", "/CIDSet"});
        }
        const bool embedded = descriptor.isDictionary() && (descriptor.hasKey("/FontFile") ||
                                                            descriptor.hasKey("/FontFile2") ||
                                                            descriptor.hasKey("/FontFile3"));
        if (!embedded) {
            OH name = f.getKey("/BaseFont");
            std::string n = name.isName() ? name.getName().substr(1) : std::string("(unnamed)");
            if (const auto plus = n.find('+'); plus == 6) {
                n = n.substr(plus + 1);  // (a subset's tag)
            }
            fontsMissing.insert(n);
        }
    }

    void image(OH img, bool defaultCmyk) {
        if (!img.isStream() || !once(img)) {
            return;
        }
        OH d = img.getDict();
        if (OH i = d.getKey("/Interpolate"); i.isBool() && i.getBoolValue()) {
            d.replaceKey("/Interpolate", OH::newBool(false));  // (6.2.8: no smoothing flag; viewers may still smooth)
        }
        removeKeys(d, {"/Alternates", "/OPI"});
        if (!(d.getKey("/ImageMask").isBool() && d.getKey("/ImageMask").getBoolValue()) &&
            cmykSpace(d.getKey("/ColorSpace")) && !defaultCmyk) {
            problem(Problem::Cmyk);
        }
        image(d.getKey("/SMask"), defaultCmyk);
        image(d.getKey("/Mask"), defaultCmyk);
    }

    void form(OH x) {
        OH d = x.getDict();
        removeKeys(d, {"/OPI", "/PS"});
        if (isName(d.getKey("/Subtype2"), "/PS")) {
            problem(Problem::PostScript);
        }
        if (d.hasKey("/Ref")) {
            problem(Problem::Reference);
        }
        OH res = d.getKey("/Resources");
        if (OH group = d.getKey("/Group"); group.isDictionary() && cmykSpace(group.getKey("/CS"))) {
            problem(Problem::Cmyk);
        }
        resources(res);
        content(x, hasDefaultCmyk(res));
    }

    void xobject(OH x, bool defaultCmyk) {
        if (!x.isStream()) {
            return;
        }
        OH subtype = x.getDict().getKey("/Subtype");
        if (isName(subtype, "/Image")) {
            image(x, defaultCmyk);
        } else if (!once(x)) {
            return;
        } else if (isName(subtype, "/Form")) {
            form(x);
        } else if (isName(subtype, "/PS")) {
            problem(Problem::PostScript);
        }
    }

    void graphicsState(OH gs) {
        if (!gs.isDictionary() || !once(gs)) {
            return;
        }
        removeKeys(gs, {"/TR", "/HTP"});  // (device dependent: transfer functions, halftone origin)
        if (gs.hasKey("/TR2") && !isName(gs.getKey("/TR2"), "/Default")) {
            gs.replaceKey("/TR2", OH::newName("/Default"));
        }
        if (gs.hasKey("/HT") && !isName(gs.getKey("/HT"), "/Default")) {
            gs.removeKey("/HT");
        }
        if (OH mask = gs.getKey("/SMask"); mask.isDictionary()) {
            xobject(mask.getKey("/G"), false);
        }
    }

    void pattern(OH p, bool defaultCmyk) {
        if (!once(p)) {
            return;
        }
        if (p.isStream()) {  // tiling
            OH res = p.getDict().getKey("/Resources");
            resources(res);
            content(p, hasDefaultCmyk(res));
        } else if (p.isDictionary()) {
            shading(p.getKey("/Shading"), defaultCmyk);
            graphicsState(p.getKey("/ExtGState"));
        }
    }

    void shading(OH s, bool defaultCmyk) {
        OH d = s.isStream() ? s.getDict() : s;
        if (d.isDictionary() && cmykSpace(d.getKey("/ColorSpace")) && !defaultCmyk) {
            problem(Problem::Cmyk);
        }
    }

    void appearance(OH ap) {
        if (ap.isStream()) {
            if (once(ap)) {
                form(ap);
            }
        } else if (ap.isDictionary()) {
            for (const auto& k: ap.getKeys()) {  // (appearance states)
                appearance(ap.getKey(k));
            }
        }
    }

    /// The annotations of a page: repaired where possible, checked.
    void annotations(OH pageObj) {
        OH annots = pageObj.getKey("/Annots");
        if (!annots.isArray()) {
            return;
        }
        OH kept = OH::newArray();
        bool changed = false;
        for (int i = 0; i < annots.getArrayNItems(); ++i) {
            OH a = annots.getArrayItem(i);
            if (!a.isDictionary()) {
                changed = true;
                continue;
            }
            OH subtype = a.getKey("/Subtype");
            const std::string kind = subtype.isName() ? subtype.getName() : std::string();
            if (kind == "/Popup") {
                kept.appendItem(a);
                continue;
            }
            static const std::set<std::string> forbidden = {"/Sound", "/Movie", "/Screen", "/3D", "/RichMedia",
                                                            "/FileAttachment"};
            if (forbidden.count(kind)) {
                problem(Problem::AnnotKind);
            }
            long long flags = a.getKey("/F").isInteger() ? a.getKey("/F").getIntValue() : 0;
            if (flags & (1 | 2 | 32 | 256)) {  // invisible, hidden, no view, toggle no view: never shown
                removedHidden = true;
                changed = true;
                continue;
            }
            flags |= 4;  // print
            if (kind == "/Text") {
                flags |= 8 | 16;  // no zoom, no rotate (a note's icon)
            }
            a.replaceKey("/F", OH::newInteger(flags));
            if (a.hasKey("/AA")) {
                a.removeKey("/AA");
                removedActions = true;
            }
            if (a.hasKey("/A") && (kind == "/Widget" || forbiddenAction(a.getKey("/A")))) {
                a.removeKey("/A");  // (a form field's action: 6.4.1 forbids every one)
                removedActions = true;
            }
            OH ap = a.getKey("/AP");
            if (ap.isDictionary()) {
                removeKeys(ap, {"/D", "/R"});  // (6.3.3: only the normal appearance)
            }
            bool emptyRect = false;
            if (OH rect = a.getKey("/Rect"); rect.isArray() && rect.getArrayNItems() == 4) {
                const auto r = rect.getArrayAsRectangle();
                emptyRect = r.llx == r.urx || r.lly == r.ury;
            }
            if (ap.isDictionary() && ap.hasKey("/N")) {
                if (kind == "/Widget" && ap.getKey("/N").isStream() && fieldType(a) == "/Btn") {
                    problem(Problem::NoAppearance);  // (6.3.3: a button's appearance has states)
                }
                appearance(ap.getKey("/N"));
            } else if (kind != "/Link" && !emptyRect) {
                problem(Problem::NoAppearance);
            }
            kept.appendItem(a);
        }
        if (changed) {
            pageObj.replaceKey("/Annots", kept);
        }
    }
};

/// Outline items: actions PDF/A forbids are removed.
bool cleanOutline(OH item, std::set<QPDFObjGen>& seen) {
    bool removed = false;
    for (int guard = 0; item.isDictionary() && guard < 100000; ++guard) {
        if (item.isIndirect() && !seen.insert(item.getObjGen()).second) {
            break;
        }
        if (forbiddenAction(item.getKey("/A"))) {
            item.removeKey("/A");
            removed = true;
        }
        removed |= cleanOutline(item.getKey("/First"), seen);
        item = item.getKey("/Next");
    }
    return removed;
}

/// Form fields: no additional actions.
bool cleanFields(OH fields, int depth = 0) {
    bool removed = false;
    if (!fields.isArray() || depth > 32) {
        return false;
    }
    for (int i = 0; i < fields.getArrayNItems(); ++i) {
        OH f = fields.getArrayItem(i);
        if (!f.isDictionary()) {
            continue;
        }
        if (f.hasKey("/AA")) {
            f.removeKey("/AA");
            removed = true;
        }
        if (forbiddenAction(f.getKey("/A"))) {
            f.removeKey("/A");
            removed = true;
        }
        removed |= cleanFields(f.getKey("/Kids"), depth + 1);
    }
    return removed;
}

std::string pagesText(const std::set<int>& pages) {
    std::string s;
    int n = 0;
    for (int p: pages) {
        if (p <= 0) {
            continue;
        }
        if (++n > 5) {
            s += ", …";
            break;
        }
        s += (s.empty() ? "" : ", ") + std::to_string(p);
    }
    if (s.empty()) {
        return s;
    }
    return n == 1 ? FS(_F(" (page {1})") % s) : FS(_F(" (pages {1})") % s);
}

struct Dates {
    std::string pdf, xmp;
};
Dates now() {
    std::time_t t = std::time(nullptr);
    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &t);
#else
    gmtime_r(&t, &tm);
#endif
    char a[40], b[40];
    std::strftime(a, sizeof a, "D:%Y%m%d%H%M%S+00'00'", &tm);
    std::strftime(b, sizeof b, "%Y-%m-%dT%H:%M:%S+00:00", &tm);
    return {a, b};
}

std::string xmlEscape(const std::string& s) {
    std::string out;
    for (char c: s) {
        switch (c) {
            case '&': out += "&amp;"; break;
            case '<': out += "&lt;"; break;
            case '>': out += "&gt;"; break;
            case '"': out += "&quot;"; break;
            case '\'': out += "&apos;"; break;
            default:
                if (static_cast<unsigned char>(c) >= 0x20 || c == '\n' || c == '\t') {
                    out += c;
                }
        }
    }
    return out;
}

std::string textOf(OH info, const char* key) {
    OH v = info.isDictionary() ? info.getKey(key) : OH::newNull();
    return v.isString() ? v.getUTF8Value() : std::string();
}

/// The XMP packet: the same title, author, subject, keywords, tools and dates as the document information.
std::string xmp(const std::map<std::string, std::string>& info, const Dates& d, bool pdfa) {
    std::ostringstream x;
    x << "<?xpacket begin=\"\xEF\xBB\xBF\" id=\"W5M0MpCehiHzreSzNTczkc9d\"?>\n"
      << "<x:xmpmeta xmlns:x=\"adobe:ns:meta/\">\n"
      << " <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
      << "  <rdf:Description rdf:about=\"\"\n"
      << "    xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
      << "    xmlns:xmp=\"http://ns.adobe.com/xap/1.0/\"\n"
      << "    xmlns:pdf=\"http://ns.adobe.com/pdf/1.3/\"\n"
      << "    xmlns:pdfaid=\"http://www.aiim.org/pdfa/ns/id/\">\n"
      << "   <dc:format>application/pdf</dc:format>\n";
    auto get = [&](const char* k) {
        auto it = info.find(k);
        return it == info.end() ? std::string() : it->second;
    };
    if (const auto t = get("/Title"); !t.empty()) {
        x << "   <dc:title><rdf:Alt><rdf:li xml:lang=\"x-default\">" << xmlEscape(t) << "</rdf:li></rdf:Alt></dc:title>\n";
    }
    if (const auto a = get("/Author"); !a.empty()) {
        x << "   <dc:creator><rdf:Seq><rdf:li>" << xmlEscape(a) << "</rdf:li></rdf:Seq></dc:creator>\n";
    }
    if (const auto s = get("/Subject"); !s.empty()) {
        x << "   <dc:description><rdf:Alt><rdf:li xml:lang=\"x-default\">" << xmlEscape(s)
          << "</rdf:li></rdf:Alt></dc:description>\n";
    }
    if (const auto k = get("/Keywords"); !k.empty()) {
        x << "   <pdf:Keywords>" << xmlEscape(k) << "</pdf:Keywords>\n";
    }
    x << "   <xmp:CreatorTool>" << xmlEscape(get("/Creator")) << "</xmp:CreatorTool>\n"
      << "   <xmp:CreateDate>" << d.xmp << "</xmp:CreateDate>\n"
      << "   <xmp:ModifyDate>" << d.xmp << "</xmp:ModifyDate>\n"
      << "   <xmp:MetadataDate>" << d.xmp << "</xmp:MetadataDate>\n"
      << "   <pdf:Producer>" << xmlEscape(get("/Producer")) << "</pdf:Producer>\n";
    if (pdfa) {
        x << "   <pdfaid:part>3</pdfaid:part>\n"
          << "   <pdfaid:conformance>B</pdfaid:conformance>\n";
    }
    x << "  </rdf:Description>\n"
      << " </rdf:RDF>\n"
      << "</x:xmpmeta>\n";
    for (int i = 0; i < 20; ++i) {  // (padding, so the metadata can be edited in place)
        x << "                                                                                                    \n";
    }
    x << "<?xpacket end=\"w\"?>";
    return x.str();
}

}  // namespace

bool dropPdfAClaim(QPDF& pdf) {
    OH meta = pdf.getRoot().getKey("/Metadata");
    if (!meta.isStream()) {
        return false;
    }
    std::string xmp;
    try {
        auto buffer = meta.getStreamData(qpdf_dl_all);
        xmp.assign(reinterpret_cast<const char*>(buffer->getBuffer()), buffer->getSize());
    } catch (const std::exception&) {
        return false;
    }
    if (xmp.find("pdfaid:") == std::string::npos) {
        return false;
    }
    // As elements (<pdfaid:part>2</pdfaid:part>) and as attributes (pdfaid:part="2"); the schema's description in a
    // pdfaExtension block (pdfaSchema:prefix>pdfaid<) is not a claim and stays
    static const std::regex element(R"(<pdfaid:(part|conformance|amd|rev)\b[^>]*?(/>|>[^<]*</pdfaid:\1\s*>))");
    static const std::regex attribute(R"(\s+pdfaid:(part|conformance|amd|rev)\s*=\s*("[^"]*"|'[^']*'))");
    std::string out = std::regex_replace(std::regex_replace(xmp, element, ""), attribute, "");
    if (out == xmp) {
        return false;
    }
    meta.replaceStreamData(out, OH::newNull(), OH::newNull());
    return true;
}

const std::string& srgbProfile() {
    static const std::string bytes(reinterpret_cast<const char*>(SRGB_ICC), SRGB_ICC_SIZE);
    return bytes;
}

fs::path suggestedFile(const fs::path& document) {
    fs::path stem = document.filename();
    stem.replace_extension();
    for (const char* tail: {".notes", ".archive"}) {
        if (lower(stem.extension().string()) == tail) {
            stem.replace_extension();
        }
    }
    fs::path file = document.parent_path() / stem;
    file += ".archive.pdf";
    std::error_code ec;
    for (int n = 2; fs::exists(file, ec) && fs::equivalent(file, document, ec) && n < 1000; ++n) {
        file = document.parent_path() / stem;
        file += ".archive (" + std::to_string(n) + ").pdf";
    }
    return file;
}

Report conform(QPDF& pdf, const Metadata& meta) {
    Report report;
    Walker w;
    OH root = pdf.getRoot();
    const Dates dates = now();

    // --- the pages: everything they show
    QPDFPageDocumentHelper helper(pdf);
    helper.pushInheritedAttributesToPage();
    for (auto& page: helper.getAllPages()) {
        ++w.page;
        OH p = page.getObjectHandle();
        if (p.hasKey("/AA")) {
            p.removeKey("/AA");
            w.removedActions = true;
        }
        removeKeys(p, {"/OutputIntents", "/PresSteps"});
        OH res = p.getKey("/Resources");
        w.resources(res);
        if (OH group = p.getKey("/Group"); group.isDictionary() && cmykSpace(group.getKey("/CS"))) {
            w.problem(Problem::Cmyk);
        }
        if (OH contents = p.getKey("/Contents"); contents.isStream() || contents.isArray()) {
            w.content(contents, Walker::hasDefaultCmyk(res));
        }
        w.annotations(p);
    }
    w.page = 0;

    // --- the document: no JavaScript, no automatic actions, forms without XFA, optional content named
    if (root.hasKey("/AA")) {
        root.removeKey("/AA");
        w.removedActions = true;
    }
    if (OH open = root.getKey("/OpenAction"); open.isDictionary() && forbiddenAction(open)) {
        root.removeKey("/OpenAction");
        w.removedActions = true;
    }
    if (OH names = root.getKey("/Names"); names.isDictionary() && names.hasKey("/JavaScript")) {
        names.removeKey("/JavaScript");
        w.removedActions = true;
    }
    removeKeys(root, {"/Perms", "/NeedsRendering", "/Requirements"});
    if (OH form = root.getKey("/AcroForm"); form.isDictionary()) {
        removeKeys(form, {"/NeedAppearances", "/XFA"});
        w.removedActions |= cleanFields(form.getKey("/Fields"));
    }
    {
        std::set<QPDFObjGen> seen;
        if (OH outlines = root.getKey("/Outlines"); outlines.isDictionary()) {
            w.removedActions |= cleanOutline(outlines.getKey("/First"), seen);
        }
    }
    if (OH oc = root.getKey("/OCProperties"); oc.isDictionary()) {
        std::vector<OH> configs;
        if (oc.getKey("/D").isDictionary()) {
            configs.push_back(oc.getKey("/D"));
        }
        if (OH more = oc.getKey("/Configs"); more.isArray()) {
            for (int i = 0; i < more.getArrayNItems(); ++i) {
                configs.push_back(more.getArrayItem(i));
            }
        }
        int n = 0;
        for (OH c: configs) {
            if (!c.isDictionary()) {
                continue;
            }
            ++n;
            if (!c.getKey("/Name").isString()) {
                c.replaceKey("/Name", OH::newString(n == 1 ? "Default" : "Configuration " + std::to_string(n)));
            }
            removeKeys(c, {"/AS"});
        }
    }

    // --- streams: no LZW (written again, decoded), none stored outside the file
    for (OH o: pdf.getAllObjects()) {
        if (!o.isStream()) {
            continue;
        }
        OH d = o.getDict();
        if (hasName(d.getKey("/Filter"), {"/LZWDecode"})) {
            report.recompress = true;
        }
        if (d.hasKey("/F") || d.hasKey("/FFilter") || d.hasKey("/FDecodeParms")) {
            w.problem(Problem::External);
        }
    }

    // --- embedded files: each an associated file of the document (PDF/A-3, 6.8)
    {
        OH af = OH::newArray();
        std::set<QPDFObjGen> inAf;
        if (OH old = root.getKey("/AF"); old.isArray()) {
            for (int i = 0; i < old.getArrayNItems(); ++i) {
                af.appendItem(old.getArrayItem(i));
                if (old.getArrayItem(i).isIndirect()) {
                    inAf.insert(old.getArrayItem(i).getObjGen());
                }
            }
        }
        QPDFEmbeddedFileDocumentHelper efdh(pdf);
        for (const auto& [name, spec]: efdh.getEmbeddedFiles()) {
            OH s = spec->getObjectHandle();
            if (!s.getKey("/F").isString()) {
                s.replaceKey("/F", OH::newUnicodeString(name));
            }
            if (!s.getKey("/UF").isString()) {
                s.replaceKey("/UF", OH::newUnicodeString(s.getKey("/F").getUTF8Value()));
            }
            if (!s.getKey("/AFRelationship").isName()) {
                s.replaceKey("/AFRelationship", OH::newName("/Unspecified"));
            }
            OH stream = spec->getEmbeddedFileStream();
            if (stream.isStream()) {
                QPDFEFStreamObjectHelper ef(stream);
                if (ef.getSubtype().empty()) {
                    ef.setSubtype("application/octet-stream");
                }
                if (ef.getModDate().empty()) {
                    ef.setModDate(dates.pdf);
                }
            }
            if (!s.isIndirect()) {
                continue;  // (name trees hold them indirectly; qpdf's helper makes them so)
            }
            if (inAf.insert(s.getObjGen()).second) {
                af.appendItem(s);
            }
        }
        if (af.getArrayNItems() > 0) {
            root.replaceKey("/AF", af);
        }
    }

    // --- the verdict
    if (!w.fontsMissing.empty()) {
        std::string list;
        int n = 0;
        for (const auto& f: w.fontsMissing) {
            if (++n > 8) {
                list += ", …";
                break;
            }
            list += (list.empty() ? "" : ", ") + f;
        }
        report.problems.push_back(FS(_F("The source PDF has fonts that are not embedded: {1}") % list));
    }
    for (const auto& [p, pages]: w.problems) {
        std::string text;
        switch (p) {
            case Problem::Cmyk: text = _("The source PDF uses CMYK colours without a colour profile"); break;
            case Problem::NoAppearance:
                text = _("The source PDF has annotations or form fields without a complete appearance");
                break;
            case Problem::AnnotKind:
                text = _("The source PDF has annotations PDF/A does not allow (sound, movie, 3D, attached files)");
                break;
            case Problem::PostScript: text = _("The source PDF contains PostScript"); break;
            case Problem::Reference: text = _("The source PDF shows pages of other files (reference XObjects)"); break;
            case Problem::External: text = _("The source PDF has data stored in other files"); break;
            case Problem::Inline: text = _("The source PDF has inline images PDF/A does not allow"); break;
        }
        report.problems.push_back(text + pagesText(pages));
    }
    if (w.removedActions) {
        report.adjusted.push_back(_("JavaScript and actions PDF/A does not allow were removed"));
    }
    if (w.removedHidden) {
        report.adjusted.push_back(_("Hidden annotations were removed"));
    }
    report.pdfa = report.problems.empty();

    // --- document information and its XMP metadata (the same values)
    OH oldInfo = pdf.getTrailer().getKey("/Info");
    std::map<std::string, std::string> info;
    info["/Title"] = !meta.title.empty() ? meta.title : textOf(oldInfo, "/Title");
    if (info["/Title"].empty()) {
        info["/Title"] = meta.fallbackTitle;
    }
    for (const char* k: {"/Author", "/Subject", "/Keywords"}) {
        info[k] = textOf(oldInfo, k);
    }
    info["/Creator"] = PROJECT_STRING;
    info["/Producer"] = std::string(PROJECT_STRING) + " + QPDF " + QPDF_VERSION;
    OH newInfo = OH::newDictionary();
    for (const auto& [k, v]: info) {
        if (!v.empty()) {
            newInfo.replaceKey(k, OH::newUnicodeString(v));
        }
    }
    newInfo.replaceKey("/CreationDate", OH::newString(dates.pdf));
    newInfo.replaceKey("/ModDate", OH::newString(dates.pdf));
    pdf.getTrailer().replaceKey("/Info", pdf.makeIndirectObject(newInfo));

    OH metadata = OH::newStream(&pdf, xmp(info, dates, report.pdfa));
    metadata.getDict().replaceKey("/Type", OH::newName("/Metadata"));
    metadata.getDict().replaceKey("/Subtype", OH::newName("/XML"));
    root.replaceKey("/Metadata", metadata);

    // --- the output intent: sRGB, with its profile
    OH icc = OH::newStream(&pdf, srgbProfile());
    icc.getDict().replaceKey("/N", OH::newInteger(3));
    OH intent = OH::newDictionary();
    intent.replaceKey("/Type", OH::newName("/OutputIntent"));
    intent.replaceKey("/S", OH::newName("/GTS_PDFA1"));
    intent.replaceKey("/OutputConditionIdentifier", OH::newString("sRGB IEC61966-2.1"));
    intent.replaceKey("/RegistryName", OH::newString("http://www.color.org"));
    intent.replaceKey("/Info", OH::newString("sRGB IEC61966-2.1"));
    intent.replaceKey("/DestOutputProfile", icc);
    OH intents = OH::newArray();
    intents.appendItem(pdf.makeIndirectObject(intent));
    root.replaceKey("/OutputIntents", intents);
    return report;
}

}  // namespace xqt::ArchivePdf
